export const coreSearchKeywords = [
  'Mzansi News',
  'Latest News',
  'South Africa News',
  'South Africa Latest News',
  'Africa News',
  'Africa Latest News',
  'BDL World News',
  'World News',
  'Politics News',
  'Celebrity News',
  'Sports News',
  'Breaking News',
  'Breaking News South Africa',
  'News Today',
  'Headlines Today',
  'Live News Updates',
  'Trending News',
  'Current Affairs',
  'BDL News Online',
  'bdlnews.online',
] as const

export const categorySearchKeywords: Record<string, string[]> = {
  world: [
    'BDL World News',
    'World News',
    'Latest News',
    'Breaking News',
    'International News',
    'Global Headlines',
  ],
  politics: [
    'Politics News',
    'Breaking News South Africa',
    'South Africa News',
    'South Africa Latest News',
    'Africa News',
    'Government News',
    'Election News',
  ],
  business: [
    'Business News',
    'South Africa News',
    'Economy News',
    'Markets News',
    'Finance News',
    'Latest News',
  ],
  technology: [
    'Technology News',
    'Latest News',
    'AI News',
    'Innovation News',
    'South Africa News',
  ],
  sports: [
    'Sports News',
    'Mzansi News',
    'South Africa News',
    'Latest News',
    'Breaking News South Africa',
  ],
  entertainment: [
    'Celebrity News',
    'Entertainment News',
    'Mzansi News',
    'Latest News',
    'Culture News',
  ],
  africa: [
    'Africa News',
    'Africa Latest News',
    'Mzansi News',
    'South Africa News',
    'South Africa Latest News',
    'African Headlines',
  ],
  opinion: [
    'Latest News',
    'South Africa News',
    'Africa News',
    'Analysis',
    'Commentary',
  ],
}
