export const siteConfig = {
  name: 'BDL News',
  shortName: 'BDL',
  legalName: 'BDL Corporation',
  parentBrand: 'Burdolar',
  parentBrandFull: 'Burdolar Corporation',
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://bdlnews.online',
  domain: 'bdlnews.online',
  description:
    'Independent digital news platform covering breaking news, South African news, African news, world news, business, technology, sports, entertainment, and current affairs.',
  tagline: 'Global stories, sharply edited',
  locale: 'en_ZA',
  language: 'en',
  email: 'burdolar@gmail.com',
  phone: '+27736701175',
  founder: {
    name: 'Zama Shange',
    jobTitle: 'Founder & Editor-in-Chief',
    slug: 'zama-shange',
    nationality: 'South African',
    description:
      'Zama Shange is the founder of BDL News and Burdolar, an entrepreneur building South Africa and Africa\'s leading AI-powered digital news platform.',
    sameAs: [
      'https://x.com/zamashange',
      'https://www.linkedin.com/in/zama-shange',
      'https://bdlcorp.africa',
    ],
  },
  organization: {
    alternateName: [
      'BDL',
      'BDL News Online',
      'bdlnews.online',
      'Burdolar News',
      'Burdolar Media',
      'BDL Corp',
      'BDL Corporation',
      'BDL News South Africa',
      'BDL News Africa',
    ],
    parentOrganization: {
      name: 'Burdolar Corporation',
      alternateName: ['Burdolar', 'Burdolar Media', 'BDL Corp'],
      url: 'https://bdlcorp.africa',
    },
    areaServed: ['South Africa', 'Africa', 'World'],
    knowsAbout: [
      'Breaking News',
      'South African News',
      'African News',
      'World News',
      'Politics',
      'Business',
      'Technology',
      'Artificial Intelligence',
      'Sports',
      'Entertainment',
      'Current Affairs',
    ],
  },
  social: {
    twitter: '@bdlnews',
  },
  defaultOgImage: '/favicon.png',
  keywords: [
    'BDL News',
    'BDL News Online',
    'bdlnews.online',
    'BDL',
    'Burdolar',
    'Burdolar News',
    'Burdolar Media',
    'BDL Corporation',
    'BDL Corp',
    'Zama Shange',
    'Zama Shange Founder',
    'BDL South Africa',
    'BDL Africa',
    'Breaking News',
    'Latest News',
    'Mzansi News',
    'South Africa News',
    'South Africa Latest News',
    'Africa News',
    'Africa Latest News',
    'BDL World News',
    'World News',
    'Politics News',
    'Celebrity News',
    'Sports News',
    'Breaking News South Africa',
    'South African News',
    'African News',
    'World News',
    'Politics News',
    'Business News',
    'Technology News',
    'AI News',
    'Sports News',
    'Entertainment News',
    'Trending News',
    'Current Affairs',
    'News Today',
    'Headlines Today',
    'Live News Updates',
    'Artificial Intelligence',
    'ChatGPT',
    'OpenAI',
    'Gemini AI',
    'Claude AI',
    'Microsoft Copilot',
    'AI Tools',
    'Future Technology',
    'Digital Innovation',
  ],
} as const

export function absoluteUrl(path = '/') {
  const base = siteConfig.url.replace(/\/$/, '')
  const normalized = path.startsWith('/') ? path : `/${path}`
  return `${base}${normalized}`
}
